require:
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'log/**/*'
    - 'tmp/**/*'
    - '**/Gemfile'
    - 'vendor/**/*'

Layout/EmptyLinesAroundArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'app/models/concerns/*'
    - 'app/controllers/concerns/*'

Metrics/ClassLength:
  Max: 140
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 17

Naming/FileName:
  Exclude:
    - 'Capfile'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/StringMethods:
  Enabled: true

Layout/LineLength:
  Enabled: true